### ISSUE TITLE
how to send mail ?

### ISSUE THREAD

**Issue by suriyaJaay** [JeffreyRosselle/angular-contact-component#1]
Hi,

Could you pls help me on this. am struggling to configure nodemailer with angular 2.  i've came across your project. seems perfect. could you pls update this project with nodemailer to send and receive mail?

lot of Thanks

**Comment by JeffreyRosselle** [comment]
Unfortunatly I have no knowlegde of Nodejs.
De code is calling a backend, which in my case would be in .Net and uses Mognet.Sendgrid Nuget package.
https://thecodegarden.net/mognet-mail-nuget
